require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-minitest
  - rubocop-capybara
  # - rubocop-graphql
AllCops:
  SuggestExtensions: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/MissingSuper:
  Enabled: false  
Naming/MethodParameterName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false  
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false