require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-minitest
  - rubocop-capybara
  # - rubocop-graphql
AllCops:
  SuggestExtensions: false
  # I just wanted to exclude ops dir because it sends rubocop into infinite loop
  # but it looks like Exclude is not merged with the default. Therefore I copied
  # here the default config obtained with `bundle exec rubocop:dump`
  Exclude:
    - 'ops/**/*'
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "app/assets/**/*"
    - "bin/*"
    - "db/*schema.rb"
    - "log/**/*"
    - "public/**/*"
    - "storage/**/*"
Bundler/DuplicatedGroup:
  Enabled: false
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/MissingSuper:
  Enabled: false  
Naming/MethodParameterName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false  
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  # this can be re-enabled when we switch to ruby >= 3.1
  EnforcedShorthandSyntax: never

# Layout/IndentationStyle:
#   EnforcedStyle: spaces
#   Enabled: true
# Layout/IndentationWidth:
#   Enabled: true

Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Security/MarshalLoad:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false
