---

- name: Patch app src code (directories)
  tags:
    - people.src.patch
  ansible.posix.synchronize:
    src: '../{{ item }}/'
    dest: '{{ people.srcdir }}/{{ item }}/'
  with_items:
    - app
    - config
    - db
    - lib
    - public
    - vendor
  notify: reload-people

- name: Patch app src code (files)
  tags:
    - people.src.patch
  ansible.builtin.copy:
    src: '../{{ item }}'
    dest: '{{ people.srcdir }}/{{ item }}'
  with_items:
    - VERSION
  notify: reload-people

- name: Run Migration
  tags:
    - people.src.patch
  containers.podman.podman_container_exec:
    name: peoapp
    command: ./bin/rails db:migrate

- name: Load new UI translations from source files
  tags:
    - people.src.patch
  containers.podman.podman_container_exec:
    name: peoapp
    command: ./bin/rails admin:load_translations

- name: Nuke dev database for the app
  tags:
    - people.db.reseed
  ansible.builtin.shell: |
    echo "DROP DATABASE people" | podman exec -i mariadb mariadb -u root --password={{ _secrets.mariadb.root_password }}
    echo "CREATE DATABASE people" | podman exec -i mariadb mariadb -u root --password={{ _secrets.mariadb.root_password }}
    podman exec peoapp ./bin/rails db:migrate
    podman exec peoapp ./bin/rails db:seed
    podman exec peoapp bin/rails data:courses
