---

- name: Ensure traefik config file for keycloak service (untill we find out how to with labels...)
  ansible.builtin.copy:
    dest: "{{ traefik.config }}/keycloak.yml"
    content: |
      http:
        routers:
          keycloak:
            tls: true
            service: keycloak
            rule: Host(`{{ people.keycloak.host }}`)
        services:
          keycloak:
            loadBalancer:
              servers:
                - 
                  url: http://keycloak:{{ people.keycloak.port }}

- name: Ensure keycloak image
  containers.podman.podman_image:
    name: "quay.io/keycloak/keycloak:{{ keycloak_version }}"

- name: Ensure keycloak service
  containers.podman.podman_container:
    command:
      - start-dev
      - --import-realm
    name: keycloak
    image: "quay.io/keycloak/keycloak:{{ keycloak_version }}"
    env:
      # https://www.keycloak.org/server/all-config
      KC_HOSTNAME: "https://{{ people.keycloak.host }}"
      KC_HTTP_ENABLED: "false"
      KC_HTTP_PORT: "{{ people.keycloak.port }}"
      KC_DB: mariadb
      KC_DB_URL: "jdbc:mariadb://mariadb:3306/keycloak"
      KC_DB_USERNAME: "{{ _secrets.keycloak.db_user }}"
      KC_DB_PASSWORD: "{{ _secrets.keycloak.db_password }}"
      KEYCLOAK_ADMIN: "{{ _secrets.keycloak.admin_user }}"
      KEYCLOAK_ADMIN_PASSWORD: "{{ _secrets.keycloak.admin_password }}"
    # ports:
    #   - "0.0.0.0:{{ people.keycloak.port }}:{{ people.keycloak.port }}"
    state: started
    network: 
      - traefik
      - people


#   keycloak:
#     image: quay.io/keycloak/keycloak:25.0.0
#     command:
#       - start-dev
#       - --import-realm
#     environment:
#       KC_HOSTNAME: "https://keycloak.dev.jkldsa.com"
#       # KC_HOSTNAME_PORT: 443
#       KC_HTTP_ENABLED: false
#       KC_DB: mariadb
#       KC_DB_URL: jdbc:mariadb://mariadb:3306/keycloak
#       KC_DB_USERNAME: keycloak
#       KC_DB_PASSWORD: mariadb
#       KEYCLOAK_ADMIN: admin
#       KEYCLOAK_ADMIN_PASSWORD: admin
#     # ports:
#     #   # Since the Keycloak password is easy to guess, opening up this
#     #   # port further than localhost is *not* recommended.
#     #   - "${KCPORTEXT:-127.0.0.1:8080:}8080"
#     labels:
#       # keycloak
#       - traefik.docker.network=traefik
#       - traefik.http.services.kc.loadbalancer.server.port=8080
#       - traefik.http.routers.kc.rule=Host("keycloak.${DOMAIN:-dev.jkldsa.com}")
#       - traefik.http.routers.kc.tls=true
#       # # keycloak management interface
#       # - traefik.http.services.kcm.loadbalancer.server.port=9000
#       # - traefik.http.routers.kcm.rule=Host("kcm.${DOMAIN:-dev.jkldsa.com}")
#       # - traefik.http.routers.kcm.tls=true
#     volumes:
#       - ./keycloak/import:/opt/keycloak/data/import
#     networks:
#       - traefik
#       - default



# KEYCLOAK_HOSTNAME