---
- name: ensure directories for people app and dependencies
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ people.storage }}"
    - "{{ people.filecache }}"
    - "{{ people.mariadb.data }}"
    - "{{ people.mariadb.init }}"

