---
- name: ensure directories for people app and dependencies
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ people.storage }}"
    - "{{ people.filecache }}"
    - "{{ mariadb.data }}"
    - "{{ mariadb.init }}"

- name: ensure bin dir for utility scripts
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/bin"
    state: directory

- name: ensure utility scripts
  ansible.builtin.template:
    src: "bin/{{ item }}"
    dest: "/home/{{ ansible_user }}/bin/{{ item }}"
    mode: 0755
  with_items:
    - peopledb
