---

- name: People source code
  ansible.builtin.git:
    repo: "{{ people.repo }}"
    dest: "{{ people.srcdir }}"
    version: "{{ people.branch }}"
    force: true
  tags:
    - people.src

- name: Checkout dependencies source code
  ansible.builtin.shell:
    chdir: "{{ people.srcdir }}"
    # cmd: "make gems elements"

- name: People source code
  ansible.builtin.git:
    repo: "{{ people.repo }}"
    dest: "{{ people.srcdir }}"
    version: "{{ people.branch }}"
    force: true
  tags:
    - people.src

- name: Determine VERSION number from git
  ansible.builtin.shell:
    chdir: "{{ people.srcdir }}"
    cmd: "/usr/bin/git tag -l --sort=creatordate | tail -n 1"
  register: git_version
  tags:
    - people.src
    - people.run
    - people.run.app

- name: Create VERSION file
  ansible.builtin.copy:
    dest: "{{ people.srcdir }}/VERSION"
    content: "{{ git_version.stdout | trim }}"
  tags:
    - people.src

- name: Store people src code version as fact
  ansible.builtin.set_fact:
    people_image_version: "{{ PEOPLE_VERSION | default(git_version.stdout | trim) }}"
  tags:
    - people.src
    - people.run
    - people.run.app

- name: Debug image version
  ansible.builtin.debug:
    var: people_image_version
  tags:
    - people.src
    - people.run
    - people.run.app

- name: Complete code with external depenencies
  ansible.builtin.shell:
    chdir: "{{ people.srcdir }}"
    cmd: "make gems"
  tags:
    - people.src
    - people.run


- name: Build people app image
  containers.podman.podman_image:
    name: "people:{{ people_image_version }}"
    path: "{{ people.srcdir }}"
    force: "{{ people_image_version == 'latest' }}"
  tags:
    - people.src
