---

- name: People source code
  ansible.builtin.git:
    repo: "{{ people.repo }}"
    dest: "{{ people.srcdir }}"
    version: "{{ people.branch }}"
    force: true
  tags:
    - people.src

- name: Create VERSION file
  ansible.builtin.shell:
    chdir: "{{ people.srcdir }}"
    cmd: "git tag -l --sort=creatordate | tail -n 1 > VERSION"
  tags:
    - people.src

- name: Read people src code version
  ansible.builtin.slurp:
    src: "{{ people.srcdir }}/VERSION"
  register: slurped_version
  tags:
    - people.src
    - people.run

- name: Store people src code version as fact 
  ansible.builtin.set_fact:
    people_image_version: "{{ PEOPLE_VERSION | default(slurped_version.content | ansible.builtin.b64decode) }}"
  tags:
    - people.src
    - people.run

- name: Debug image version
  ansible.builtin.debug:
    var: people_image_version
  tags:
    - people.src
    - people.run

- name: Build people app image
  containers.podman.podman_image:
    name: "people:{{ people_image_version }}"
    path: "{{ people.srcdir }}"
    force: "{{ people_image_version == 'latest' }}"
  tags:
    - people.src

