people:
  branch: "{{ PEOPLE_BRANCH | default('master') }}"
  enable_api_cache: "{{ ENABLE_API_CACHE | default(false) }}"
  enable_webmock: "{{ ENABLE_WEBMOCK | default(false) }}"
  env: "{{ RAILS_ENV | default('development') }}"
  filecache: "{{ DATA_BASEDIR }}/people/filecache"
  hostname: "{{ PEOPLE_HOSTNAME | default('people.epfl.ch') }}"
  oidc:
    hostname: "{{ OIDC_HOSTNAME }}"
    realm: "{{ OIDC_REALM | default('rails') }}"
    path: "{{ OIDC_PATH | default('/realms/' ~ (OIDC_REALM | default('rails'))) }}"
    endpoint: "{{ OIDC_ENDPOINT | default((OIDC_PATH | default('/realms/' ~ (OIDC_REALM | default('rails')))) ~ '/protocol/openid-connect/auth') }}"
    identifier: "{{ OIDC_IDENTIFIER | default('hello_rails') }}"
    url: "{{ OIDC_URL | default('https://' ~ OIDC_HOSTNAME ~ (OIDC_PATH | default('realms/' ~ (OIDC_REALM | default('rails'))) )) }}"
  port: 3000
  redis: "{{ (SELECT_CACHE == 'local_redis') | ternary('redis://cache:6379/0', REDIS_URL) }}"
  repo: "https://github.com/epfl-si/people2023.git"
  srcdir: "{{ PEOPLE_SRCDIR }}"
  storage: "{{ DATA_BASEDIR }}/people/storage"
  mariadb:
    data: "{{ DATA_BASEDIR }}/people/mariadb/data"
    init: "{{ DATA_BASEDIR }}/people/mariadb/init"
  keycloak:
    port: 9091
    host: "{{ OIDC_HOSTNAME }}"
  whoami:
    port: 9092