---

- name: SSL certificates for DOMAINS (glob certificates)
  copy:
    src: '{{ traefik.certs_src }}/{{ item }}'
    dest: "{{ traefik.basedir }}/certs/"
  with_items: "{{ DOMAINS }}"

- name: SSL certificates for DOMAINS configuration
  copy:
    content: |
      tls:
        certificates:
          {% for item in DOMAINS %}
      - certFile: /etc/traefik/certs/{{ item }}/fullchain.pem
            keyFile: /etc/traefik/certs/{{ item }}/privkey.pem
          {% endfor %}
    dest: "{{ traefik.basedir }}/config/certfiles.yml"
