---
- include_vars: traefik_vars.yml
  tags: always

- name: Traefik vars 
  debug:
    var: traefik

- name: Setup requirements for Traefik
  tags:
    - traefik.setup
  import_tasks:
    file: setup.yml

- name: Traefik Configuration
  tags:
    - traefik.config
  import_tasks:
    file: config.yml

# The certificates are served by the ingress traefik.
# - name: Traefik Certificates
#   tags:
#     - traefik.config
#     - traefik.config.certs
#   import_tasks:
#     file: config_certs.yml
#   when: traefik.with_https

- name: Traefik Run
  tags:
    - traefik.run
  import_tasks:
    file: run.yml
