---
- name: Register ansible_user uid
  ansible.builtin.command: id -u
  register: ansible_user_uid

- name: Debug ansible_user_uid
  ansible.builtin.debug:
    var: ansible_user_uid.stdout 

- name: Ensure podman socket
  ansible.builtin.systemd_service:
    name: podman.socket
    state: started
    scope: user
    enabled: yes

- name: traefik docker network
  containers.podman.podman_network:
    name: traefik

- name: Ensure traefik image
  containers.podman.podman_image:
    name: "docker.io/library/traefik:{{ traefik_version }}"

- name: Ensure traefik containers is running
  containers.podman.podman_container:
    name: traefik
    image: "traefik:{{ traefik_version }}"
    ports:
      - "0.0.0.0:{{ ports.traefik_http }}:{{ ports.traefik_http }}"
      - "0.0.0.0:{{ ports.traefik_https }}:{{ ports.traefik_https }}"
    volumes: 
      - "{{ traefik.basedir }}:/etc/traefik"      
      - "/run{{ (ansible_user == 'root') | ternary('', '/user/') }}{{(ansible_user == 'root') | ternary('', ansible_user_uid.stdout )}}/podman/podman.sock:/var/run/docker.sock"
    # restart_policy: unless-stopped
    # force_restart: "{{ traefik_static_config.changed | default(false) or 'traefik.reload' in ansible_run_tags  }}"
    state: started
    # generate_systemd: false
      # restart_sec: 10
    network:
      traefik

