default: &default
  adapter: mysql2
  host: mariadb
  username: people
  password: mariadb

development:
  <<: *default
  database: people

test:
  <<: *default
  database: testpeople

# 12 factor in production
production:
  adapter: mysql2
  database: <%= ENV.fetch('DATABASE_NAME', 'please_do_not_die') %>
  host:     <%= ENV.fetch('DATABASE_HOST', 'please_do_not_die') %>
  username: <%= ENV.fetch('DATABASE_USER', 'please_do_not_die') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'please_do_not_die') %>

# ---------------------------------------------------------- External/Legacy DBs

legacy_dev_cv:
  <<: *default
  database: cv

legacy_prod_cv:
  adapter: mysql2
  host:     <%= ENV.fetch('CV_DATABASE_HOST', 'please_do_not_die') %>
  username: <%= ENV.fetch('CV_DATABASE_USER', 'please_do_not_die') %>
  password: <%= ENV.fetch('CV_DATABASE_PASSWORD', 'please_do_not_die') %>
  database: cv

