# OpenID Connect (OIDC) configuration for the app
# Available as `Rails.application.config_for(:oidc)`

production:
  server: <%= ENV.fetch('ENTRA_SERVER', 'login.microsoftonline.com') %>
  base_path: /<%= ENV.fetch('ENTRA_TENANT_ID') %>/oauth2/v2.0
  auth_path: /authorize
  token_path: /token"
  client_id: <%= ENV.fetch('ENTRA_CLIENT_ID') %>
  secret: <%= ENV.fetch('ENTRA_SECRET') %>

<% if ENV.fetch("USE_KEYCLOAK", false) %>
development: &dev_oidc_config
  server: <%= ENV.fetch('KC_SERVER', 'keycloak.dev.jkdlsa.com') %>
  base_path: /realms/rails/protocol/openid-connect
  auth_path: /auth
  token_path: /token
  client_id: hello_rails
  # secret: ""
<% else %>
development: &dev_oidc_config
  server: <%= ENV.fetch('ENTRA_SERVER', 'login.microsoftonline.com') %>
  base_path: /<%= ENV.fetch('ENTRA_TENANT_ID') %>/oauth2/v2.0
  auth_path: /authorize
  token_path: /token
  client_id: <%= ENV.fetch('ENTRA_CLIENT_ID') %>
  secret: <%= ENV.fetch('ENTRA_SECRET') %>
<% end %>

test:
  <<: *dev_oidc_config
