- name: Config ssh
  tags:
    - system.config
    - system.config.ssh
  import_tasks:
    file: config_ssh.yml

- name: System Install
  tags:
    - system.install
  import_tasks:
    file: install.yml

- name: Config podman
  tags:
    - system.config
    - system.config.podman
  import_tasks:
    file: config_podman.yml

# - name: Reset system
#   tags:
#     - never
#     - reset
#   include_tasks:
#     file: reset.yml
#     apply:
#       tags:
#         - never
#         - reset

