- name: Ensure quay-pull-secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: quay-pull-secret
        namespace: "{{ namespace }}"
      data:
        .dockerconfigjson: "{{ quay_pull_config | to_json | b64encode }}"

- name: Ensure puller ServiceAccount linked to quay-pull-secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: puller
        namespace: "{{ namespace }}"
      secrets:
        - name: quay-pull-secret
      imagePullSecrets:
        - name: quay-pull-secret
