---

- name: OpenShift Ingress for people RoR webapp
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ kid.app }}"
        namespace: "{{ namespace }}"
        labels:
          # this label MUST NOT be removed although it is a label on a static resource
          route: "{{ people.visibility }}"
      spec:
        host: "{{ hosts.people }}"
        to:
          kind: Service
          name: "{{ kid.app }}"
        port:
          targetPort: 8080
        tls:
          termination: edge


- name: OpenShift Ingress for people RoR webapp
  when: hosts.personnes is defined
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ kid.app }}-personnes"
        namespace: "{{ namespace }}"
        labels:
          # this label MUST NOT be removed although it is a label on a static resource
          route: "{{ people.visibility }}"
      spec:
        host: "{{ hosts.personnes }}"
        to:
          kind: Service
          name: "{{ kid.app }}"
        port:
          targetPort: 8080
        tls:
          termination: edge

- name: OpenShift Ingress for legacy app proxy
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ kid.legacy }}"
        namespace: "{{ namespace }}"
        labels:
          # this label MUST NOT be removed although it is a label on a static resource
          route: "{{ people.visibility }}"
      spec:
        host: "{{ hosts.people }}"
        path: "/legacy"
        to:
          kind: Service
          name: "{{ kid.legacy }}"
        port:
          targetPort: 8181
        tls:
          termination: edge

- name: OpenShift Ingress for photos taken directly from the legacy app
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ kid.legacy_photo }}"
        namespace: "{{ namespace }}"
        labels:
          # this label MUST NOT be removed although it is a label on a static resource
          route: "{{ people.visibility }}"
      spec:
        host: "{{ hosts.people }}"
        path: "/private"
        to:
          kind: Service
          name: "{{ kid.legacy }}"
        port:
          targetPort: 8181
        tls:
          termination: edge

- name: OpenShift Routes taken directly from the legacy app
  with_items:
    # Keeping this for a while in case we need to revert back
    # - path: "/cgi-bin/wsgetpeople"
    #   name: "{{ kid.legacy_cgibin }}-people"
    #   state: present
    - path: "/cgi-bin/wsgetPhoto"
      name: "{{ kid.legacy_cgibin }}-photo"
      state: present
    - path: "/cgi-bin/"
      name: "{{ kid.legacy_cgibin }}"
      state: absent
  kubernetes.core.k8s:
    state: "{{ item.state }}"
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ namespace }}"
        labels:
          # this label MUST NOT be removed although it is a label on a static resource
          route: "{{ people.visibility }}"
      spec:
        host: "{{ hosts.people }}"
        path: "{{ item.path }}"
        to:
          kind: Service
          name: "{{ kid.legacy }}"
        port:
          targetPort: 8181
        tls:
          termination: edge

- name: Ensure people-webapp service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ kid.app }}"
        namespace: "{{ namespace }}"
      spec:
        selector:
          kid: "{{ kid.app }}"
        ports:
          - protocol: TCP
            port: 8080
            targetPort: 8080

- name: Ensure legacy app proxy service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ kid.legacy }}"
        namespace: "{{ namespace }}"
      spec:
        selector:
          kid: "{{ kid.legacy }}"
        ports:
          - protocol: TCP
            port: 8181
            targetPort: 8181
