- name: Deploy Redis (Valkey) instance
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: people-redis
        namespace: "{{ app_namespace }}"
        labels:
          app: people
          component: redis
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: people
            component: redis
        template:
          metadata:
            labels:
              app: people
              component: redis
          spec:
            serviceAccountName: puller
            imagePullSecrets:
              - name: quay-pull-secret
            containers:
              - name: redis
                image: "{{ redis_image }}"
                command: ["valkey-server", "--maxmemory", "32mb"]
                ports:
                  - containerPort: 6379
                resources:
                  requests:
                    cpu: "100m"
                    memory: "64Mi"
                  limits:
                    cpu: "200m"
                    memory: "128Mi"
                volumeMounts:
                  - name: redis-volume
                    mountPath: /srv/filecache
            volumes:
              - name: redis-volume
                persistentVolumeClaim:
                  claimName: people-redis

- name: Expose Redis service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: people-redis
        namespace: "{{ app_namespace }}"
        labels:
          app: people
          component: redis
      spec:
        ports:
          - port: 6379
            targetPort: 6379
        selector:
          app: people
          component: redis