
- name: Deploy Redis (Valkey) instance
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ kid.redis }}"
        namespace: "{{ namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            kid: "{{ kid.redis }}"
        template:
          metadata:
            labels:
              kid: "{{ kid.redis }}"
          spec:
            serviceAccountName: puller
            imagePullSecrets:
              - name: quay-pull-secret
            containers:
              - name: redis
                image: "{{ redis.image }}"
                command: ["valkey-server", "--maxmemory", "{{ redis.memory }}mb", "--save", "{{ redis.save.time | string }}", "{{ redis.save.data | string }}"]
                ports:
                  - containerPort: 6379 # ANSIBLE+K8S=PURE SHIT! "{{ redis.port | int }}"
                resources: "{{ helpers.resources }}"
                volumeMounts:
                  - name: "{{ kid.redis }}-data"
                    mountPath: /data
            volumes:
              - name: "{{ kid.redis }}-data"
                persistentVolumeClaim:
                  claimName: "{{ kid.redis }}"

- name: Expose Redis service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ kid.redis }}"
        namespace: "{{ namespace }}"
      spec:
        ports:
          - port: 6379 # ANSIBLE+K8S=PURE SHIT! "{{ redis.port | int }}"
            targetPort: 6379 # ANSIBLE+K8S=PURE SHIT! "{{ redis.port | int }}"
        selector:
          kid: "{{ kid.redis }}"
