
- name: Deploy Redis (Valkey) instance
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: people-redis
        namespace: "{{ namespace }}"
        labels:
          app: people
          component: redis
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: people
            component: redis
        template:
          metadata:
            labels:
              app: people
              component: redis
          spec:
            serviceAccountName: puller
            imagePullSecrets:
              - name: quay-pull-secret
            containers:
              - name: redis
                image: "{{ redis.image }}"
                command: ["valkey-server", "--maxmemory", "{{ redis.memory }}mb", "--save", "{{ redis.save.time }}", "{{ redis.save.data }}"]
                ports:
                  - containerPort: 6379 # ANSIBLE+K8S=PURE SHIT! "{{ redis.port | int }}"
                resources:
                  requests:
                    cpu: "100m" # WTF is this unit ?
                    memory: "{{ redis.memory }}Mi"
                  limits:
                    cpu: "200m" # WTF is this unit ?
                    memory: "{{ redis.alloc_memory }}Mi"
                volumeMounts:
                  - name: redis-volume
                    mountPath: /data
            volumes:
              - name: redis-volume
                persistentVolumeClaim:
                  claimName: people-redis

- name: Expose Redis service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ redis.service }}"
        namespace: "{{ namespace }}"
        labels:
          app: people
          component: redis
      spec:
        ports:
          - port: 6379 # ANSIBLE+K8S=PURE SHIT! "{{ redis.port | int }}"
            targetPort: 6379 # ANSIBLE+K8S=PURE SHIT! "{{ redis.port | int }}"
        selector:
          app: people
          component: redis
