---

people_config:
  # ------------------------------ deployment-independent mandatory ENV vars
  RAILS_ENV: "{{ people.env }}"
  SUPERUSERS: "{{ _secrets.people.superusers }}"

  # -------------------------------------------------- with ok default value
  # APP_HOSTNAME: people.epfl.ch
  APP_HOSTNAME: "{{ hosts.people }}"
  RAILS_SERVE_STATIC_FILES: "yes"
  # ENABLE_DIRECT_UPLOADS: false
  # HIDE_ENS_ACCREDDS: true
  # INTRANET_RE: '^128\.17[89]'
  # RAILS_LOG_LEVEL: info in prod
  # if REDIS_CACHE is defined then redis is used otherwise default to memory
  # note that in dev cache is enabled only if presence of tmp/caching-dev.txt
  REDIS_CACHE: "{{ people.redis }}"
  # SEEDS_PATH: db/seeds/data
  # USE_LOCAL_ELEMENTS: false
  USE_LOCAL_ELEMENTS: "{{ people.use_local_elements }}"
  ERROR_PAGES: "{{ people.error_pages }}"
  WSGETPEOPLE_CACHE: "{{ people.wsgetpeople_cache }}"

  # ---------------------------------------------------- transition specific
  ENABLE_ADOPTION: "{{ people.enable_adoption }}"
  LEGACY_BASE_URL: "{{ people.legacy_base_url }}"
  LEGACY_RW_URL: "{{ people.legacy_rw_url }}"

  # LEGACY_PAGES_CACHE: 2days

  ATELA_KEY: "{{ _secrets.atela_key }}"
  CAMIPRO_PHOTO_KEY: "{{ _secrets.camipro_photo_key }}"
  CAMIPRO_PHOTO_HOST: "{{ people.camipro_host }}"
  ENABLE_API_CACHE: "{{ people.enable_api_cache }}"
  EPFLAPI_BACKEND_URL: "{{ people.api_url }}"
  ISA_URL: "{{ people.isa_url }}"

  NAME_CHANGE_REQUEST_EMAIL: "{{ people.name_change_request_email }}"

  # Ollama / OpenAI
  OLLAMA_URL: "{{ people.ollama_url }}"
  OPENAI_API_KEY: "{{ _secrets.inference.key }}"
  OPENAI_BASE_URL: "{{ people.openai_url }}"

  # --> oidc.yml
  ENTRA_TENANT_ID: "{{ _secrets.entra_oidc.tenant_id }}"
  ENTRA_CLIENT_ID: "{{ _secrets.entra_oidc.client_id }}"
  ENTRA_SECRET: "{{ _secrets.entra_oidc.secret }}"
  USE_KEYCLOAK: "false"

people_secrets:
  # DB_MAIN_HOST: "{{ _secrets.db.main.server  | b64encode}}"
  # DB_MAIN_PORT: "{{ _secrets.db.main.port | b64encode }}"
  # DB_MAIN_NAME: "{{ _secrets.db.main.dbname  | b64encode}}"
  # DB_MAIN_USER: "{{ _secrets.db.main.username  | b64encode}}"
  # DB_MAIN_PASSWORD: "{{ _secrets.db.main.password  | b64encode}}"
  DB_MAIN_HOST: "{{ _secrets.db.main_adm.server  | b64encode}}"
  DB_MAIN_PORT: "{{ _secrets.db.main_adm.port | b64encode }}"
  DB_MAIN_NAME: "{{ _secrets.db.main_adm.dbname  | b64encode}}"
  DB_MAIN_USER: "{{ _secrets.db.main_adm.username  | b64encode}}"
  DB_MAIN_PASSWORD: "{{ _secrets.db.main_adm.password  | b64encode}}"

  DB_QUEUE_HOST: "{{ kid.db | b64encode}}"
  DB_QUEUE_PORT: "{{ _secrets.db.queue.port | b64encode }}"
  DB_QUEUE_NAME: "{{ _secrets.db.queue.dbname  | b64encode}}"
  DB_QUEUE_USER: "{{ _secrets.db.queue.username  | b64encode}}"
  DB_QUEUE_PASSWORD: "{{ _secrets.db.queue.password  | b64encode}}"

  DB_WORK_HOST: "{{ kid.db | b64encode}}"
  DB_WORK_PORT: "{{ _secrets.db.work.port | b64encode }}"
  DB_WORK_NAME: "{{ _secrets.db.work.dbname  | b64encode}}"
  DB_WORK_USER: "{{ _secrets.db.work.username  | b64encode}}"
  DB_WORK_PASSWORD: "{{ _secrets.db.work.password  | b64encode}}"

  DB_LEGACY_HOST: "{{ _secrets.db.legacy.server  | b64encode}}"
  DB_LEGACY_PORT: "{{ _secrets.db.legacy.port | b64encode }}"
  DB_LEGACY_NAME: "{{ _secrets.db.legacy.dbname  | b64encode}}"
  DB_LEGACY_USER: "{{ _secrets.db.legacy.username  | b64encode}}"
  DB_LEGACY_PASSWORD: "{{ _secrets.db.legacy.password  | b64encode}}"

  ENTRA_SECRET: "{{ _secrets.entra_oidc.secret | b64encode }}"
  EPFLAPI_PASSWORD: "{{ _secrets.api.password | b64encode }}"
  CAMIPRO_PHOTO_KEY: "{{ _secrets.camipro_photo_key | b64encode }}"
  OASIS_BASEURL: "{{ _secrets.oasis.baseurl | b64encode }}"
  OASIS_TOKEN: "{{ _secrets.oasis.token | b64encode }}"
  SECRET_KEY_BASE: "{{ _secrets.secret_key_base | b64encode }}"

people_config_signature: "{{ people_config | to_json | md5 }}"
people_secrets_signature: "{{ people_secrets | to_json | md5 }}"
