---
# var order partially dictated by dependencies
namespace: "{{ OC_NAMESPACE }}"

# Kubernetes name (see README.md for naming convention)
kid:
  app:          "app-{{ RUNENV }}-{{ RELEASE }}"
  app_config:   "appconfig-{{ RUNENV }}-{{ RELEASE }}"
  app_secrets:  "appsecrets-{{ RUNENV }}"
  db:           "db-{{ RUNENV }}"
  db_user:      "dbuser-{{ RUNENV }}"
  db_secrets:   "dbsecrets-{{ RUNENV }}"
  db_queue:     "dbqueue-{{ RUNENV }}"
  db_work:      "dbwork-{{ RUNENV }}"
  jobs:         "jobs-{{ RUNENV }}-{{ RELEASE }}"
  legacy:       "legacy-{{ RUNENV }}-{{ RELEASE }}"
  legacy_photo: "legacyphoto-{{ RUNENV }}-{{ RELEASE }}"
  legacy_cgibin: "legacycgibin-{{ RUNENV }}-{{ RELEASE }}"
  legacy_cache: "legacycache-{{ RUNENV }}-{{ RELEASE }}"
  legacy_data:  "legacydata-{{ RUNENV }}-{{ RELEASE }}"
  logs:         "logs-{{ RUNENV }}-{{ RELEASE }}"
  redis:        "redis-{{ RUNENV }}"
  uploads:      "uploads-{{ RUNENV }}"

helpers:
  resources:
    limits:
      # cpu:
      memory: "8192Mi"
    requests:
      cpu: "10m"
      memory: "1Mi"

# Quay Pull robot credentials
_pull_robot_credential: "{{ _secrets.quay.pull_robot.name }}:{{ _secrets.quay.pull_robot.token }}"
quay_pull_config:
  auths:
    "quay-its.epfl.ch":
      "auth": "{{ _pull_robot_credential | b64encode }}"

mariadb:
  disk: 5 # Gb

redis:
  # Note that redis image is configured to mirror the official one
  image: quay-its.epfl.ch/svc0033/valkey
  port: "{{ ports.redis }}"
  memory: 3072 # Mb
  alloc_memory: 4096 # Mb
  disk: 5 # Gb
  service: "{{ kid.redis }}"
  save:
    time: 300 # permanent storage dump period [seconds]
    data: 512 # number of updated keys before dump to permanent storage is trggered

legacy:
  image: "quay-its.epfl.ch/svc0033/peolegacy:{{ legacy_version }}"
  cache_size: "2Gi"
  data_size: "2Gi"

people:
  app_replicas: "{{ APP_REPLICAS | default('1') | int }}"
  job_replicas: "{{ JOB_REPLICAS | default('0') | int }}"
  visibility: "{{ APP_VISIBILITY | default('private') }}"
  api_url: "{{ EPFLAPI_BACKEND_URL | default('https://api.epfl.ch/v1') }}"
  camipro_host: "{{ CAMIPRO_PHOTO_HOST | default('camipro-photos.epfl.ch') }}"
  enable_adoption: "{{ ENABLE_ADOPTION | default('false') }}"
  enable_api_cache: "{{ ENABLE_API_CACHE | default('true') }}"
  env: "{{ RAILS_ENV | default('production') }}"
  error_pages: "{{ ERROR_PAGES | default('prod') }}"
  hostname: "{{ APP_HOSTNAME }}"
  image: "quay-its.epfl.ch/svc0033/people:{{ people_version }}-prod"
  isa_url: "{{ ISA_URL | default('https://isa.epfl.ch/services') }}"
  legacy_base_url: "https://{{ APP_HOSTNAME }}/legacy"
  legacy_rw_url: "{{ LEGACY_PATCH_URL | default('https://test-people.epfl.ch') }}"
  name_change_request_email: "{{ NAME_CHANGE_REQUEST_EMAIL | default('name.change@groupes.epfl.ch') }}"
  ollama_url: "{{ OLLAMA_URL | default('false') }}"
  openai_url: "{{ OPENAI_URL | default('https://inference-dev.rcp.epfl.ch/v1') }}"
  redis: "redis://{{ redis.service }}:{{ ports.redis }}/0"
  repo: "https://github.com/epfl-si/people2.git"
  # storage: "{{ DATA_BASEDIR }}/people/storage"
  use_local_elements: "{{ USE_LOCAL_ELEMENTS | default('true') }}"
  wsgetpeople_cache: "{{ WSGETPEOPLE_CACHE | default('21600') }}"
  logs_size: 5 #Gb

route:
  name: people
  namespace: "{{ namespace }}"
  target_service: people
  port_name: http
  termination: edge
  visibility_label: public-cf
