app_namespace: svc0033p-people

webapp_image: quay-its.epfl.ch/svc0033/people
redis_image: quay-its.epfl.ch/svc0033/valkey
mariadb_version: 11.4.3

inventory_environment: "prod"

route:
  name: people
  namespace: "{{ app_namespace }}"
  target_service: people
  port_name: http
  termination: edge
  visibility_label: public-cf

keybase_path: keybase://team/epfl_people.prod/OPS/
keybase_dockerconfig_path: "{{ keybase_path }}/ops/config.json"


people_app_env:
  APP_HOSTNAME: "https://people-next.epfl.ch"
  RAILS_ENV: "production"
  DEFAULT_URL: "https://people-next.epfl.ch"
  ENABLE_API_CACHE: "true"
  ENABLE_WEBMOCK: "false"
  USE_LOCAL_ELEMENTS: "false"
  REDIS_CACHE: "redis://people-redis:6379/0"
  OFFLINE_CACHEDIR: "/srv/filecache"
  FORCE_AUDIENCE: "false"
  SHOW_ERROR_PAGES: "no"
  SILENT_TRANSLATION_ERR: "no"
  ISA_URL: "https://isa-test.epfl.ch/services"
  LEGACY_SERVER_URL: "https://personnes.epfl.ch"
  ENABLE_ADOPTION: "true"
  SECRET_KEY_BASE: "thisisstrongpasswworkd"
  ENTRA_TENANT_ID: "f6c2556a-c4fb-4ab1-a2c7-9e220df11c43"
  ENTRA_CLIENT_ID: "9ca0fc49-17e2-449d-850d-552513993ab4"
  EPFLAPI_BACKEND_URL: "https://api.epfl.ch/v1"
  RAILS_SERVE_STATIC_FILES: "true"
  CAMIPRO_PHOTO_HOST: "camipro-photos.epfl.ch"
  TMPDIR: "/tmp"

