---
# var order partially dictated by dependencies
namespace: "{{ OC_NAMESPACE }}"

# Quay Pull robot credentials
_pull_robot_credential: "{{ _secrets.quay.pull_robot.name }}:{{ _secrets.quay.pull_robot.token }}"
quay_pull_config:
  auths:
    "quay-its.epfl.ch":
      "auth": "{{ _pull_robot_credential | b64encode }}"

mariadb:
  disk: 5 # Gb

limits:
  cpu:
    min: "10m"
    max: "4"
  memory:
    min: "1Mi"
    max: "8192Mi"

redis:
  # Note that redis image is configured to mirror the official one
  image: quay-its.epfl.ch/svc0033/valkey
  port: "{{ ports.redis }}"
  memory: 3072 # Mb
  alloc_memory: 4096 # Mb
  disk: 5 # Gb
  service: people-redis
  save:
    time: 300 # permanent storage dump period [seconds]
    data: 512 # number of updated keys before dump to permanent storage is trggered

people:
  api_url: "{{ EPFLAPI_BACKEND_URL | default('https://api.epfl.ch/v1') }}"
  camipro_host: "{{ CAMIPRO_PHOTO_HOST | default('camipro-photos.epfl.ch') }}"
  enable_adoption: "{{ ENABLE_ADOPTION | default('false') }}"
  enable_api_cache: "{{ ENABLE_API_CACHE | default('true') }}"
  env: "{{ RAILS_ENV | default('production') }}"
  hostname: "{{ APP_HOSTNAME }}"
  image: "quay-its.epfl.ch/svc0033/people:{{ people_version }}-prod"
  isa_url: "{{ ISA_URL | default('https://isa.epfl.ch/services') }}"
  legacy_ro_url: "{{ LEGACY_BASE_URL | default('https://personnes.epfl.ch') }}"
  legacy_rw_url: "{{ LEGACY_PATCH_URL | default('https://test-people.epfl.ch') }}"
  name_change_request_email: "{{ NAME_CHANGE_REQUEST_EMAIL | default('name.change@groupes.epfl.ch') }}"
  ollama_url: "{{ OLLAMA_URL | default('false') }}"
  openai_url: "{{ OPENAI_URL | default('https://inference-dev.rcp.epfl.ch/v1') }}"
  redis: "redis://{{ redis.service }}:{{ ports.redis }}/0"
  repo: "https://github.com/epfl-si/people2.git"
  # storage: "{{ DATA_BASEDIR }}/people/storage"
  use_local_elements: "{{ USE_LOCAL_ELEMENTS | default('true') }}"

route:
  name: people
  namespace: "{{ namespace }}"
  target_service: people
  port_name: http
  termination: edge
  visibility_label: public-cf
