
_keybase_secrets:
  prod: "{{ lookup('file', '/keybase/team/epfl_people.prod/ops/secrets-prod.yml') | from_yaml }}"
  # test: "{{ lookup('file', '/keybase/team/epfl_people.test/secrets-test.yml') | from_yaml }}"

keybase_secrets: "{{ _keybase_secrets.get(inventory_environment, {}) }}"

# Credentials robot
_pull_robot_secrets: "{{ keybase_secrets.quay.pull_robot }}"
_pull_robot_credential: "{{ _pull_robot_secrets.name }}:{{ _pull_robot_secrets.token }}"

# config.json Docker
pull_secret_config:
  auths:
    "quay-its.epfl.ch":
      "auth": "{{ _pull_robot_credential | b64encode }}"