---

- name: Create or update Keycloak realm
  community.general.keycloak_realm:
    auth_client_id: admin-cli
    auth_keycloak_url: "https://{{ keycloak.host }}/"
    auth_realm: master
    auth_username: "{{ _secrets.keycloak.admin_user }}"
    auth_password: "{{ _secrets.keycloak.admin_password }}"
    id: "{{ keycloak.realm }}"
    realm: "{{ keycloak.realm }}"
    state: present
    display_name: "{{ keycloak.display_name }}"
  delegate_to: localhost


- name: Create or update Keycloak realm
  community.general.keycloak_user:
    auth_client_id: admin-cli
    auth_keycloak_url: "https://{{ keycloak.host }}/"
    auth_realm: master
    auth_username: "{{ _secrets.keycloak.admin_user }}"
    auth_password: "{{ _secrets.keycloak.admin_password }}"

    email: "{{ item.email }}"
    email_verified: true
    enabled: true
    first_name: "{{ item.first_name }}"
    last_name: "{{ item.last_name }}"
    realm: "{{ keycloak.realm }}"
    state: present
    username: "{{ item.user }}"
  delegate_to: localhost
  with_items: "{{ _secrets.keycloak.users }}"