---

- name: Traefik static configuration file
  template:
    src: "traefik.yml"
    dest: "{{ traefik.basedir }}/traefik.yml"
  register: traefik_static_config

- name: Dynamic traefik config
  template:
    src: "traefik_ingress.yml"
    dest: "{{ traefik.config }}/ingress.yml"

