http:
  routers:
    dashboard:
      rule: Host(`{{ traefik.console_hostname }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      middlewares:
        - apiauth
  middlewares:
    apiauth:
      basicAuth:
        users:
          - "{{ _secrets.traefik.auth.user }}:{{ _secrets.traefik.auth.pass | password_hash('md5') }}"
