global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

accessLog:
  format: json

{% if traefik.with_console %}
api:
  dashboard: true
{% endif %}

providers:
  file:
    directory: /etc/traefik/config
    watch: true
{% if traefik.with_docker %}
  docker:
    # endpoint: "unix:///var/run/docker.sock"
    watch: true
{% endif %}

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5

entryPoints:
  web:
    address: "0.0.0.0:{{ traefik.http_port }}"
{% if traefik.with_docker %}
    forwardedHeaders:
      insecure: true
{% endif %}
{% if traefik.with_https %}
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":{{ traefik.https_port }}"
    http:
      tls: {}

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /etc/traefik/acme/acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: "{{ traefik.email }}" 
      tlsChallenge: true
      httpChallenge:
        entryPoint: http

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/default.crt
        keyFile: /etc/traefik/certs/default.key
{% endif %}